import Head from "next/head";
import Navbar from "../components/Navbar";
import Hero from "../components/Hero";
import About from "../components/About";
import Projects from "../components/Projects";
import SkillsAndExperiences from "../components/SkillsAndExperiences";

export default function Home() {
  return (
    <div
      style={{
        background: "white",
      }}
    >
      <Head>
        <title>Rayyan Zaid | Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/portfolio/assets/about.png" />
      </Head>

      <Navbar />
      <Hero />
      <About />
      <Projects />
      <SkillsAndExperiences />
    </div>
  );
}
